In [ ]:
import pandas as pd
import os

ruta = r'C:/Users/sophi/Documents/Curso 08 - Machine learning/Trabajo en grupo/23f_scrappedDF.csv'

In [15]:
#opcional
from huggingface_hub import login
login("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")

In [2]:
df = pd.read_csv(ruta)

print(df.shape)
df.head()

(167, 7)

,title,url,pages,summary,tags,transcript,filename
0,Vista oral 2/81 del Consejo Supremo de Justici...,https://23fbuscador.rtve.es/document/ocr/1860?...,3,El juicio oral 2/81 celebrado en febrero de 19...,"['C/SG/2820/20-02-82', 'DTOR.', 'Vista oral 2/...",C/SG/2820/20-02-82\nDTOR.\n\nNOTA INFORMATIVA\...,Vista oral 281 del Consejo Supremo de Justicia...
1,Vista oral 2/81 del Consejo Supremo de Justici...,https://23fbuscador.rtve.es/document/ocr/1859?...,4,Resumen global del documento:\n\nEl documento ...,"['C/SG/2896/22-02-82', 'Vista oral 2/81', 'Con...",C/SG/2896/22-02-82\n\n# NOTA INFORMATIVA\n\nAS...,Vista oral 281 del Consejo Supremo de Justicia...
2,Vista oral 2/81 del Consejo Supremo de Justici...,https://23fbuscador.rtve.es/document/ocr/1858?...,5,Resumen global del documento:\n\nEl documento ...,"['C/SG/2992/24-02-82', 'Vista Oral 2/81', 'Con...",C/SG/2992/24-02-82\n\n# NOTA INFORMATIVA\n\nAS...,Vista oral 281 del Consejo Supremo de Justicia...
3,Vista oral 2/81 del Consejo Supremo de Justici...,https://23fbuscador.rtve.es/document/ocr/1857?...,6,El documento recoge el desarrollo de la sesión...,"['C/SG/3.081/25-02-82', 'Vista Oral 2/81', 'Co...",C/SG/3.081/25-02-82\n\n# NOTA INFORMATIVA\n\nA...,Vista oral 281 del Consejo Supremo de Justicia...
4,Vista oral 2/81 del Consejo Supremo de Justici...,https://23fbuscador.rtve.es/document/ocr/1856?...,6,Resumen global del documento sobre la sesión d...,"['C/SG/3.249/26-02-82', 'SG', 'Consejo Supremo...",C/SG/3.249/26-02-82\nSG\n\n# NOTA INFORMATIVA\...,Vista oral 281 del Consejo Supremo de Justicia...

In [3]:
df["transcript"] = df["transcript"].str.replace(r"\s+", " ", regex=True)
df["text_for_embedding"] = df["transcript"]

In [4]:
def chunk_text(text, chunk_size=500):
    words = text.split()
    chunks = []
    
    for i in range(0, len(words), chunk_size):
        chunk = " ".join(words[i:i + chunk_size])
        chunks.append(chunk)
    
    return chunks

In [5]:
df["chunks"] = df["text_for_embedding"].apply(chunk_text)

In [6]:
df_chunks = df.explode("chunks").reset_index(drop=True)

In [7]:
#limpiar los chunck vacios
df_chunks = df_chunks[df_chunks["chunks"].str.strip() != ""]

In [8]:
df_chunks.head()

,title,url,pages,summary,tags,transcript,filename,text_for_embedding,chunks
0,Vista oral 2/81 del Consejo Supremo de Justici...,https://23fbuscador.rtve.es/document/ocr/1860?...,3,El juicio oral 2/81 celebrado en febrero de 19...,"['C/SG/2820/20-02-82', 'DTOR.', 'Vista oral 2/...",C/SG/2820/20-02-82 DTOR. NOTA INFORMATIVA ASUN...,Vista oral 281 del Consejo Supremo de Justicia...,C/SG/2820/20-02-82 DTOR. NOTA INFORMATIVA ASUN...,C/SG/2820/20-02-82 DTOR. NOTA INFORMATIVA ASUN...
1,Vista oral 2/81 del Consejo Supremo de Justici...,https://23fbuscador.rtve.es/document/ocr/1860?...,3,El juicio oral 2/81 celebrado en febrero de 19...,"['C/SG/2820/20-02-82', 'DTOR.', 'Vista oral 2/...",C/SG/2820/20-02-82 DTOR. NOTA INFORMATIVA ASUN...,Vista oral 281 del Consejo Supremo de Justicia...,C/SG/2820/20-02-82 DTOR. NOTA INFORMATIVA ASUN...,Gómez Iglésias. - Menor asistencia de invitado...
2,Vista oral 2/81 del Consejo Supremo de Justici...,https://23fbuscador.rtve.es/document/ocr/1859?...,4,Resumen global del documento:\n\nEl documento ...,"['C/SG/2896/22-02-82', 'Vista oral 2/81', 'Con...",C/SG/2896/22-02-82 # NOTA INFORMATIVA ASUNTO: ...,Vista oral 281 del Consejo Supremo de Justicia...,C/SG/2896/22-02-82 # NOTA INFORMATIVA ASUNTO: ...,C/SG/2896/22-02-82 # NOTA INFORMATIVA ASUNTO: ...
3,Vista oral 2/81 del Consejo Supremo de Justici...,https://23fbuscador.rtve.es/document/ocr/1859?...,4,Resumen global del documento:\n\nEl documento ...,"['C/SG/2896/22-02-82', 'Vista oral 2/81', 'Con...",C/SG/2896/22-02-82 # NOTA INFORMATIVA ASUNTO: ...,Vista oral 281 del Consejo Supremo de Justicia...,C/SG/2896/22-02-82 # NOTA INFORMATIVA ASUNTO: ...,Primera declaración del Capitán de Intendencia...
4,Vista oral 2/81 del Consejo Supremo de Justici...,https://23fbuscador.rtve.es/document/ocr/1859?...,4,Resumen global del documento:\n\nEl documento ...,"['C/SG/2896/22-02-82', 'Vista oral 2/81', 'Con...",C/SG/2896/22-02-82 # NOTA INFORMATIVA ASUNTO: ...,Vista oral 281 del Consejo Supremo de Justicia...,C/SG/2896/22-02-82 # NOTA INFORMATIVA ASUNTO: ...,"deseable la instalación de una ""consigna"" ante..."

In [9]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')
df_chunks["embedding"] = df_chunks["chunks"].apply(lambda x: model.encode(x))

c:\Users\sophi\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\sophi\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\huggingface_hub\file_download.py:129: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\sophi\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 37746.90it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
print(df_chunks["embedding"].iloc[0])
len(df_chunks["embedding"].iloc[0])

[-2.71487106e-02  4.13078777e-02 -4.17216979e-02 -1.05394743e-01
 -5.50660193e-02 -1.66635413e-03  5.53612448e-02  9.41566080e-02
 -1.00610889e-02 -6.77507045e-03  1.27546549e-01 -4.48516272e-02
 -7.73213198e-03 -1.64145865e-02 -5.49040809e-02 -5.56257330e-02
 -5.41360304e-02 -6.01511542e-03 -1.95454769e-02  4.90354635e-02
  9.55584049e-02 -2.62694480e-03 -4.03936952e-02  5.45463972e-02
 -3.84655371e-02 -4.28020954e-02 -1.46552855e-02  8.20443220e-03
 -7.19299391e-02  1.40971243e-02  7.25521427e-03  9.91468951e-02
 -3.24744061e-02  5.48955286e-03 -2.86471918e-02 -9.46050510e-02
  1.22947535e-02 -2.07322314e-02 -7.44718313e-03  6.48042560e-02
 -4.41532992e-02 -2.45805141e-02 -6.56768531e-02 -1.50993206e-02
 -4.39382046e-02 -1.00611538e-01 -4.59513664e-02  3.86287160e-02
 -6.69308528e-02  4.16948609e-02  5.64105576e-03 -1.04034850e-02
 -3.71472314e-02  2.86507364e-02 -5.06531708e-02 -5.23967519e-02
 -4.34015244e-02 -2.60492470e-02 -3.00848344e-03  1.10764122e-02
  2.44415235e-02  4.10995744e-02  6.40624319e-04 -3.91748315e-03
 -2.68868208e-02 -3.71775739e-02  2.03922093e-02 -6.53176084e-02
 -9.30653885e-02  1.24687739e-02  1.38832763e-01 -8.69267732e-02
 -4.74828817e-02  5.75536629e-03 -9.81730074e-02 -1.41148977e-02
  2.51753759e-02  5.12519218e-02 -2.97015719e-02 -1.24029808e-01
  3.93201075e-02  8.81817937e-02  8.81263912e-02 -1.30295753e-01
 -2.71515828e-02 -2.46415678e-02 -3.18874381e-02  1.39430091e-02
  7.07903579e-02 -1.50456820e-02  6.72049820e-02  8.56116712e-02
 -1.03455251e-02 -1.57734205e-03  3.71140391e-02 -1.42064029e-02
  4.06355485e-02  5.52344024e-02 -1.44200576e-02  1.39326882e-02
  1.01756439e-01 -1.51346019e-03 -5.12325801e-02  3.29450406e-02
 -4.60783318e-02  6.44191653e-02  8.39134604e-02 -1.61146931e-02
  2.22038589e-02 -1.33467428e-02 -8.93661454e-02  2.41592969e-03
  3.42177972e-03 -4.60687876e-02 -6.73562437e-02  2.08624974e-02
 -4.54856157e-02  3.04035051e-03  6.78901076e-02  2.34405673e-03
  5.04363999e-02  1.00091603e-02 -6.80584386e-02  1.45520587e-02
  6.86266795e-02  1.01581179e-02  3.41322422e-02  1.27744850e-32
  4.03931458e-03 -1.27432626e-02 -6.00330345e-03  7.44631737e-02
  3.19052413e-02  1.49997985e-02 -5.79988360e-02  3.32143605e-02
 -5.00466898e-02 -3.38959806e-02 -1.06572039e-01  7.35936337e-04
 -3.83531675e-02 -4.13615480e-02  1.50262546e-02  1.83716454e-02
 -3.46000455e-02 -4.00554128e-02  3.83689441e-02 -1.46792096e-03
 -2.25608107e-02  4.40447107e-02  1.41302347e-02  4.54679504e-02
 -4.05491553e-02  7.25497901e-02 -7.75350258e-02 -1.22444304e-02
 -5.78231961e-02  4.07881252e-02  1.11201436e-04 -1.28430137e-02
  9.63463038e-02 -1.60892066e-02  1.81260519e-02 -2.07670573e-02
  5.94045594e-02 -1.21337725e-02 -6.54307306e-02 -6.54128045e-02
  2.41951402e-02 -2.24813186e-02  3.58108692e-02  6.75525591e-02
  4.09206748e-03 -1.53350616e-02  8.29034895e-02  4.27286997e-02
  8.90128016e-02 -1.58686861e-02 -2.13196948e-02  1.58330966e-02
 -7.54431337e-02 -2.49426998e-02 -5.98882250e-02  6.03573024e-03
 -7.26934075e-02  6.49834722e-02  2.17312351e-02 -2.00267993e-02
  6.66617900e-02  1.96881015e-02 -4.53811288e-02  5.87443076e-02
 -4.89017218e-02  2.75751110e-02 -1.03836581e-02  4.16024961e-02
  1.58584028e-01 -2.17893887e-02 -4.82031219e-02 -4.73887846e-02
  6.88568689e-03  7.85271376e-02  2.19426639e-02  5.72528057e-02
  1.26827478e-01 -6.29072718e-04 -4.32119519e-02  6.06292188e-02
 -1.32570982e-01 -1.56649183e-02 -5.58659434e-02 -1.88336279e-02
  6.40107840e-02  6.02688454e-02  1.99649553e-03  8.40974506e-03
  4.11415771e-02  6.78125918e-02  3.59118581e-02  7.98665136e-02
  2.84136869e-02 -5.71888648e-02  3.14208819e-03 -1.32946692e-32
 -7.39804208e-02 -3.16175781e-02 -2.77566388e-02 -1.68057755e-02
 -1.33446243e-03  2.21538227e-02 -2.62975097e-02 -3.30156349e-02
  1.56676751e-02 -1.17050506e-01 -7.66834691e-02 -1.62731428e-02
  4.94047403e-02 -9.10877958e-02 -3.00728809e-02  7.62300417e-02
 -7.07711279e-02  1.15320589e-02 -6.11973293e-02  2.54267976e-02
  2.20526811e-02  6.87892660e-02 -5.30715426e-03  9.63298604e-03
 -3.54170129e-02  3.57852466e-02  1.74246598e-02 -2.77070124e-02
 -2.96790283e-02  6.33041235e-03  3.42659131e-02 -1.25163645e-01
  1.19203627e-02  7.69071430e-02 -6.98860362e-02  1.75980642e-03
  8.45683664e-02 -4.18655686e-02 -3.51445526e-02  9.70623419e-02
 -8.70633218e-03  1.85421519e-02  7.90685713e-02 -1.53352953e-02
 -1.56002892e-02  5.06466404e-02 -4.11986746e-03 -8.43415037e-02
 -6.15319498e-02 -2.17403732e-02  8.32435414e-02  3.34412828e-02
 -8.21120590e-02  2.77510341e-02  6.12834767e-02 -4.03640717e-02
 -4.12639789e-02 -5.96195348e-02 -4.53338027e-02  2.97205355e-02
  7.54994452e-02  9.96613950e-02 -8.11672285e-02 -1.51528260e-02
  8.67099985e-02 -1.66170672e-02 -5.53623848e-02  2.77359672e-02
  2.84205396e-02  9.84262023e-03  1.74911198e-04 -8.32640529e-02
 -1.31361574e-01 -6.42359555e-02 -3.22084650e-02 -1.38909668e-02
 -4.58956249e-02  5.64865675e-03 -7.48215429e-03 -2.66343448e-02
 -9.26332697e-02 -8.90874192e-02  3.49871023e-03  2.45920550e-02
 -6.29565492e-03  2.03670119e-03 -2.83466484e-02 -3.32351716e-04
  1.01561531e-01  5.60250133e-02  4.84467149e-02  2.61361543e-02
  2.07885094e-02 -3.91713195e-02  3.87766777e-05 -7.16235107e-08
  3.84826921e-02 -1.46379443e-02  5.78209478e-03 -1.80649534e-02
  9.17205065e-02 -5.51724657e-02  4.79055895e-03 -2.00795662e-02
  5.09956703e-02  9.92195681e-02  3.57992239e-02 -2.49398518e-02
 -7.67568350e-02 -4.44017872e-02 -1.20116118e-02 -6.97277859e-02
 -7.27332942e-03  1.03202023e-01 -2.22666319e-02 -1.07877779e-04
 -1.52508635e-02  3.35583766e-03 -2.33515240e-02 -4.01713178e-02
 -1.57785378e-02 -3.14751752e-02 -2.85418965e-02  5.92483133e-02
  2.72210110e-02  3.18757398e-03 -3.85758765e-02  2.49511637e-02
 -3.73675488e-02 -1.19597331e-01  1.28385322e-02  1.78141482e-02
  2.78816503e-02  2.56701130e-02  1.81428622e-02 -1.36389788e-02
  3.38861085e-02 -1.61818154e-02 -3.28856930e-02  5.12552001e-02
  1.42307663e-02 -4.68974039e-02 -1.53322276e-02  2.08387766e-02
  6.26516268e-02 -6.38956055e-02 -1.42196473e-02  3.97534929e-02
  9.45395231e-03  7.44970441e-02 -3.18277702e-02 -8.52945596e-02
  1.30567176e-04  4.88184281e-02 -2.98161339e-03 -2.52080373e-02
  7.76176006e-02  8.23882595e-02  3.22943106e-02 -5.83352670e-02]

384

In [17]:
embeddings = model.encode(
    df_chunks["chunks"].tolist(),
    show_progress_bar=True
)

df_chunks["embedding"] = embeddings

Batches: 100%|██████████| 25/25 [00:12<00:00,  1.96it/s]

In [ ]:
import numpy as np
df_chunks["embedding"] = list(embeddings)

In [21]:
df_chunks.head()

,title,url,pages,summary,tags,transcript,filename,text_for_embedding,chunks,embedding
0,Vista oral 2/81 del Consejo Supremo de Justici...,https://23fbuscador.rtve.es/document/ocr/1860?...,3,El juicio oral 2/81 celebrado en febrero de 19...,"['C/SG/2820/20-02-82', 'DTOR.', 'Vista oral 2/...",C/SG/2820/20-02-82 DTOR. NOTA INFORMATIVA ASUN...,Vista oral 281 del Consejo Supremo de Justicia...,C/SG/2820/20-02-82 DTOR. NOTA INFORMATIVA ASUN...,C/SG/2820/20-02-82 DTOR. NOTA INFORMATIVA ASUN...,"[-0.027148727, 0.04130788, -0.04172172, -0.105..."
1,Vista oral 2/81 del Consejo Supremo de Justici...,https://23fbuscador.rtve.es/document/ocr/1860?...,3,El juicio oral 2/81 celebrado en febrero de 19...,"['C/SG/2820/20-02-82', 'DTOR.', 'Vista oral 2/...",C/SG/2820/20-02-82 DTOR. NOTA INFORMATIVA ASUN...,Vista oral 281 del Consejo Supremo de Justicia...,C/SG/2820/20-02-82 DTOR. NOTA INFORMATIVA ASUN...,Gómez Iglésias. - Menor asistencia de invitado...,"[0.027866922, 0.10246259, 0.010371909, -0.0166..."
2,Vista oral 2/81 del Consejo Supremo de Justici...,https://23fbuscador.rtve.es/document/ocr/1859?...,4,Resumen global del documento:\n\nEl documento ...,"['C/SG/2896/22-02-82', 'Vista oral 2/81', 'Con...",C/SG/2896/22-02-82 # NOTA INFORMATIVA ASUNTO: ...,Vista oral 281 del Consejo Supremo de Justicia...,C/SG/2896/22-02-82 # NOTA INFORMATIVA ASUNTO: ...,C/SG/2896/22-02-82 # NOTA INFORMATIVA ASUNTO: ...,"[-0.028903669, 0.046620682, -0.000816554, -0.0..."
3,Vista oral 2/81 del Consejo Supremo de Justici...,https://23fbuscador.rtve.es/document/ocr/1859?...,4,Resumen global del documento:\n\nEl documento ...,"['C/SG/2896/22-02-82', 'Vista oral 2/81', 'Con...",C/SG/2896/22-02-82 # NOTA INFORMATIVA ASUNTO: ...,Vista oral 281 del Consejo Supremo de Justicia...,C/SG/2896/22-02-82 # NOTA INFORMATIVA ASUNTO: ...,Primera declaración del Capitán de Intendencia...,"[-0.025484566, 0.035273522, 0.0072249514, -0.0..."
4,Vista oral 2/81 del Consejo Supremo de Justici...,https://23fbuscador.rtve.es/document/ocr/1859?...,4,Resumen global del documento:\n\nEl documento ...,"['C/SG/2896/22-02-82', 'Vista oral 2/81', 'Con...",C/SG/2896/22-02-82 # NOTA INFORMATIVA ASUNTO: ...,Vista oral 281 del Consejo Supremo de Justicia...,C/SG/2896/22-02-82 # NOTA INFORMATIVA ASUNTO: ...,"deseable la instalación de una ""consigna"" ante...","[0.016134173, 0.0069032665, -0.08394172, 0.005..."

In [23]:
guardar = r'C:/Users/sophi/Documents/Curso 08 - Machine learning/Trabajo en grupo/'
df_chunks.to_csv(guardar+'embeddings.csv', index=False)